---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - pip install jmespath
install:
  - pip install molecule
  - pip install docker-py
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
