---

- name: optionally install local mail transport agent
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ mailman3_mta }}"
  when: mailman3_mta_install

- name: optionally install local database server for mailman3
  apt:
    pkg: "{{ 'postgresql' if mailman3_db_backend == 'pgsql' else 'mariadb-server' }}"
    state: present
  when:
    - mailman3_db_install
    - mailman3_db_backend == 'pgsql' or mailman3_db_backend == 'mysql'

- name: optionally install local database server for mailman3-web
  apt:
    pkg: "{{ 'postgresql' if mailman3_web_db_backend == 'pgsql' else 'mariadb-server' }}"
    state: present
  when:
    - mailman3_db_install
    - mailman3_web_db_backend == 'pgsql' or mailman3_web_db_backend == 'mysql'
