---

- name: install role dependencies
  apt:
    pkg: python-jmespath
    state: present

- import_tasks: dependencies.yml
  tags:
    - mailman3-dependencies

- import_tasks: mailman3.yml
  tags:
    - mailman3

- import_tasks: postfix.yml
  when:
    - mailman3_mta == 'postfix'
    - mailman3_mta_config
  tags:
    - mailman3-postfix

- import_tasks: mailman3-web.yml
  tags:
    - mailman3-web
