---

- name: restart mailman3
  service:
    name: mailman3
    state: restarted

- name: restart mailman3-web
  service:
    name: mailman3-web
    state: restarted

- name: restart exim4
  service:
    name: exim4
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted
